name: Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.1.0"
    
    - name: Terraform Init
      working-directory: Ejercicio2
      run: terraform init
      
    - name: Terraform Validate
      working-directory: Ejercicio2
      run: terraform validate
      
    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working-directory: Ejercicio2
        
    - name: Terraform Plan
      working-directory: Ejercicio2
      run: terraform plan
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        admin_principal_id: ${{ secrets.TF_VAR_ADMIN_PRINCIPAL_ID }}
        reader_principal_id: ${{ secrets.TF_VAR_READER_PRINCIPAL_ID}}
    
    - name: Terraform Apply
      working-directory: Ejercicio2
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        admin_principal_id: ${{ secrets.TF_VAR_ADMIN_PRINCIPAL_ID }}
        reader_principal_id: ${{ secrets.TF_VAR_READER_PRINCIPAL_ID}}
